config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments
belongs_to :user

 default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts

  def admin?
   role == 'admin'
 end
 def moderator?
   role == 'moderator'
 end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end



   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
     @posts = Post.all
     authorize @posts

  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post=Post.new
    authorize @post
  end
  def create
     @post = Post.new(params.require(:post).permit(:title, :body))
     @post.user = current_user

     if @post.save
       flash[:notice] = "Post was saved."
       redirect_to @post
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :new
     end
   end

  def edit
    @post=Post.find(params[:id])
    authorize @post
  end
  def update
     @post = Post.find(params[:id])
     authorize @post
     if @post.update_attributes(params.require(:post).permit(:title, :body))
       flash[:notice] = "Post was updated."
       redirect_to @post
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :edit
     end
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Bloccit", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
  </ul>
  <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>
<div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @post do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
 <% if policy(Post.new).create? %>
 <%= link_to "New Post", new_post_path, class: 'btn btn-success' %>
<% end %>

<% @posts.each do |post| %>
  <p><%= link_to post.title, post %></p>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to post.title, post %>
       </h4>
       <small>
         submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><b>
         <%= post.comments.count %> Comments
       </small>
     </div>
   </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @post do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
 <% if policy(@post).edit? %>
 <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-success' %>
 <% end %>
 <p><%= @post.body %></p>

app/views/welcome/about.html.erb
<h1>A Reddit replica</h1>
<p>Created by :Revanth</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Bloccit will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>
 